FROM python:3.11-slim

# Use an official Python runtime as a parent image, specifically the slim version to keep the image size down

# Set the working directory to /app inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
#-i https://pypi.tuna.tsinghua.edu.cn/simple
