apiVersion: v1
kind: Namespace
metadata:
  name: guance-chatbot

---

apiVersion: v1
kind: Service
metadata:
  name: guance-chatbot-service
  namespace: guance-chatbot
spec:
  type: NodePort
  selector:
    app: deployment-guance-chatbot
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30700

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-guance-chatbot
  name: guance-chatbot
  namespace: guance-chatbot
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-guance-chatbot
  template:
    metadata:
      labels:
        app: deployment-guance-chatbot
    spec:
      containers:
      - name: guance-chatbot
        image: pubrepo.guance.com/chatbot/guancedoc:1.1
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ENV_K8S_NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: ENV_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: DEEPSEEK_API_KEY
            value: 
          - name: ZHIPUAI_API_KEY
            value: 
          - name: BOT_TOPIC
            value: "guance doc"
        ports:
          - containerPort: 7000
            name: port
            protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        securityContext:
          privileged: false
        volumeMounts:
        workingDir: /app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
